# Generated by Django 5.1.5 on 2025-02-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_household_smallcommercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='city',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
