# Generated by Django 5.1.5 on 2025-02-04 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_household_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='performed_by',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='performed_by',
            field=models.ManyToManyField(related_name='maintenance_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
