# Generated by Django 5.1.5 on 2025-02-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_maintenance_performed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='performed_by',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='performed_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
